float:
  euclidean:
  - base_args:
      - '@metric'
    constructor: GustannOriginal
    disabled: true
    docker_tag: ann-benchmarks-gustann
    module: ann_benchmarks.algorithms.gustann_original
    name: gustann-original
    run_groups:
      baseline:
        arg_groups:
          - index_params:
              gustann_home: ../GustANN
              pq_size: 32
              search_memory_gb: 4
              build_memory_gb: 16
              max_degree: 128
              l_build: 200
              pivot_sample_size: 1000000
              pivot_graph_degree: 32
              pivot_graph_l_build: 50
            search_params:
              - minibatch: 64
                thread: 40
                ctx_per_thread: 1
                ef_search: 30
              - minibatch: 256
                thread: 40
                ctx_per_thread: 1
                ef_search: 30
              - minibatch: 1024
                thread: 40
                ctx_per_thread: 1
                ef_search: 30
              - minibatch: 10000
                thread: 40
                ctx_per_thread: 1
                ef_search: 30
        query_args: [[30]]
uint8:
  euclidean:
  - base_args:
      - '@metric'
    constructor: GustannOriginal
    disabled: true
    docker_tag: ann-benchmarks-gustann
    module: ann_benchmarks.algorithms.gustann_original
    name: gustann-original
    run_groups:
      baseline:
        arg_groups:
          - index_params:
              gustann_home: ../GustANN
              pq_size: 32
              search_memory_gb: 4
              build_memory_gb: 16
              max_degree: 128
              l_build: 200
              pivot_sample_size: 1000000
              pivot_graph_degree: 32
              pivot_graph_l_build: 50
            search_params:
              - minibatch: 64
                thread: 40
                ctx_per_thread: 1
                ef_search: 30
              - minibatch: 256
                thread: 40
                ctx_per_thread: 1
                ef_search: 30
              - minibatch: 1024
                thread: 40
                ctx_per_thread: 1
                ef_search: 30
              - minibatch: 10000
                thread: 40
                ctx_per_thread: 1
                ef_search: 30
        query_args: [[30]]
